### PR TITLE
reduce temporary object creation for pgsql connect

### PR DESCRIPTION
**Pull request by GitMensch**
Feel free to ignore this PR, I've just stumbled over this when stepping through the code, getting into the std::string connector two times instead of once and thought "that would be easier to debug when I can just see those values directly instead of stepping into these functions".

Performance-wise it will obviously make no difference, and likely the other drivers are similar.

BTW: I've failed to get the connection string be printed from the connection info, what is wrong in the following line?`
```
|(gdb) p conn_info.toConnectionString(false,"")
Cannot resolve method IDataSourceInfo::toConnectionString to any overloaded instance
```

Side note: maybe drop the boolean parameter and instead only checking for the std:string to be empty (currently both is done)?

### CODE REVIEW

**Comment by GitMensch** [comment]
There were changes in 081674b3c03e1b97b0a2edf854a152d765331bee but I think that's still open (and we now have some commented lines in, that may should be removed).

No priority at all, just something that has been seen during debugging.

**Comment by GitMensch** [comment]
no conflicts so I guess that minor issue is likely still open

**Comment by GitMensch** [comment]
ping @mridoni - I guess this is obsolete with the "C++ization" coming.

**Comment by mridoni** [comment]
> ping @mridoni - I guess this is still not obsolete with the "C++ization" coming.

Yes, it will be closed with v1.0.20

**Pull request closed without merging**
